/** Markdown for docs/INGEST_REPORT.md. Pure. */

export type FileStatus = "OK" | "FAIL" | "MISSING" | "SKIP";
export type FileRow = { file: string; status: FileStatus; detail: string };
export type SlotRow = {
  id: string;
  status: "OK" | "FAIL";
  durationSec: number | null;
  limitSec: number;
  timingSource: string;
  words: number;
  truthMaxErrMs: number | null;
  reason: string;
};

export type ReportInput = {
  source: string;
  packId: string;
  provenance: string;
  root: string;
  missingRequired: string[];
  missingOptional: string[];
  extra: string[];
  files: FileRow[];
  slots: SlotRow[];
  sizes: { file: string; bytes: number }[];
  budget: { perFileMb: number; packMb: number };
  outcome: string;
  ffmpeg: string;
};

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
const mb = (b: number) => (b / 1048576).toFixed(2);

export function renderReport(r: ReportInput): string {
  const ok = r.files.filter((f) => f.status === "OK").length;
  const fail = r.files.filter((f) => f.status === "FAIL" || f.status === "MISSING").length;
  const total = r.sizes.reduce((a, s) => a + s.bytes, 0);
  const largest = [...r.sizes].sort((a, b) => b.bytes - a.bytes)[0];
  const overFile = r.sizes.filter((s) => s.bytes > r.budget.perFileMb * 1048576);
  const truth = r.slots.map((s) => s.truthMaxErrMs).filter((x): x is number => x !== null);
  const lines: string[] = [
    "# INGEST_REPORT",
    "",
    "Generated by `npm run ingest`. Do not edit by hand.",
    "",
    `- Source: \`${r.source}\``,
    `- Pack id: \`${r.packId}\` · provenance: **${r.provenance}**`,
    `- Tools: ${r.ffmpeg}`,
    `- Outcome: **${r.outcome}**`,
    "",
    "## Tree check (docs/ASSET_PACK.md §1)",
    "",
    `- Missing required: ${r.missingRequired.length ? r.missingRequired.map((f) => `\`${f}\``).join(", ") : "none"}`,
    `- Missing optional: ${r.missingOptional.length ? r.missingOptional.map((f) => `\`${f}\``).join(", ") : "none"}`,
    `- Extra (ignored): ${r.extra.length ? r.extra.map((f) => `\`${f}\``).join(", ") : "none"}`,
    "",
    "## Files",
    "",
    "| file | status | detail |",
    "|---|---|---|",
    ...r.files.map((f) => `| ${esc(f.file)} | ${f.status} | ${esc(f.detail)} |`),
    "",
    `Totals: ${ok} OK, ${fail} FAIL/MISSING, ${r.files.filter((f) => f.status === "SKIP").length} skipped.`,
    "",
    "## Slots",
    "",
    "| slot | status | durationSec | limit | timing | words | max word error vs truth | reason |",
    "|---|---|---|---|---|---|---|---|",
    ...r.slots.map(
      (s) =>
        `| ${s.id} | ${s.status} | ${s.durationSec?.toFixed(3) ?? "-"} | ${s.limitSec} | ${s.timingSource || "-"} | ${s.words || "-"} | ${s.truthMaxErrMs !== null ? `${Math.round(s.truthMaxErrMs)} ms` : "-"} | ${esc(s.reason) || "-"} |`,
    ),
    "",
  ];
  if (truth.length) {
    const max = Math.max(...truth);
    lines.push(`Silence-path word timing vs truth.json: max error **${Math.round(max)} ms** over ${truth.length} slots (acceptance < 120 ms: ${max < 120 ? "PASS" : "FAIL"}).`, "");
  }
  lines.push(
    `## Output size (public/packs/${r.packId})`,
    "",
    `- Total: ${mb(total)} MB (budget ${r.budget.packMb} MB: ${total <= r.budget.packMb * 1048576 ? "PASS" : "FAIL"})`,
    `- Largest file: ${largest ? `\`${largest.file}\` ${mb(largest.bytes)} MB` : "-"} (budget ${r.budget.perFileMb} MB per file: ${overFile.length ? `FAIL (${overFile.map((s) => s.file).join(", ")})` : "PASS"})`,
    `- Files: ${r.sizes.length}`,
    "",
  );
  return lines.join("\n");
}
